packages:
  - apps/*
  - packages/*

storeDir: .pnpm-store
cacheDir: .cache/pnpm

minimumReleaseAgeExclude:
  - react-i18next@17.0.14
  - zod@4.6.5

allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  esbuild: true
  prisma: true

strictDepBuilds: true
strictPeerDependencies: true
