packages:
  - apps/*
  - packages/*

storeDir: .pnpm-store
cacheDir: .cache/pnpm

minimumReleaseAgeExclude:
  - react-i18next@17.0.14
  - zod@4.6.5

onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - prisma

strictPeerDependencies: true
